import Head from 'next/head'
import styles from './Layout.module.css'
export default function Layout(props) {
    const { children } = props
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="description" content="Wholesale jewellery store that offers a variety of custom designs made to order."></meta>
            </Head>
            <div className={styles.main_header_wrapper}>
                <div className={styles.top_elements}>
                    <nav className={styles.navbar}>
                        <a className={""} href="/">
                            <img src="./img/logo.png" className={styles.jainam_logo} alt="..." />
                        </a>
                        <div className={styles.navbar_link_group}>
                            <div className={styles.navbar_link}>
                                <a className={styles.navbar_link_label} href="/">Home</a>
                            </div>
                            <div className={styles.navbar_link}>
                                <a className={styles.navbar_link_label} href="#">About</a>
                            </div>
                            <div className={styles.navbar_link}>
                                <a className={styles.navbar_link_label} href="#">Catalogue</a>
                            </div>
                            <div className={styles.navbar_link}>
                                <a className={styles.navbar_link_label} href="/pricetab">Live Prices</a>
                            </div>
                            <div className={styles.navbar_link}>
                                <a className={styles.navbar_link_label} href="#">Blog</a>
                            </div>
                            <div className={styles.navbar_link}>
                                <a className={styles.navbar_link_label} href="#">Contact</a>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
            {children}
            <footer className={styles.footer_main_wrap}>
                <div className={styles.links_header}>SITE LINKS</div>
                <div className={styles.footer_link_wrapper}>
                    <div>
                        <div className={styles.footer_link_element}>LINK 11</div>
                        <div className={styles.footer_link_element}>LINK 12</div>
                        <div className={styles.footer_link_element}>LINK 13</div>
                        <div className={styles.footer_link_element}>LINK 14</div>
                    </div>
                    <div>
                        <div className={styles.footer_link_element}>LINK 11</div>
                        <div className={styles.footer_link_element}>LINK 12</div>
                        <div className={styles.footer_link_element}>LINK 13</div>
                        <div className={styles.footer_link_element}>LINK 14</div>
                    </div>
                    <div>
                        <div className={styles.footer_link_element}>LINK 11</div>
                        <div className={styles.footer_link_element}>LINK 12</div>
                        <div className={styles.footer_link_element}>LINK 13</div>
                        <div className={styles.footer_link_element}>LINK 14</div>
                    </div>
                    <div className={styles.socials_wrapper}>
                        <div className={styles.socials_element}>
                            <img
                            src="/img/twitter_black.png"
                            alt="Twitter Logo"
                            />
                        </div>
                    </div>
                </div>

                <div className={styles.terms_wrapper}>
                    <div>© 2021 Jainam Jewellers. All rights reserved. | View our other publications | Privacy policy | Terms of use | Take down policy.</div>
                </div>
            </footer>
        </>
    )
}