import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "./LayoutMobile.module.css";
import Sidebar from "react-sidebar";
export default function Layout(props) {
  const { children } = props;
  const [hamburger, setHam] = useState(false);
  useEffect(() => {
    /* window.addEventListener('scroll', handleScroll) */
  }, []);

  const SideBarContent = () => {
    return (
      <>
        <div className={styles.sidebarWrapperClass}>
          <div className={styles.closeButtonWrapper}>
            <div>
              <button>
                <img
                  onClick={() => {
                    setHam(false);
                  }}
                  src="/img/closeIcon.svg"
                  alt="Close button"
                />
              </button>
            </div>
          </div>
          <div className={styles.logoWrapper_sidebar}>
            <img src="/img/logo_dark.png" />
          </div>
          <div className={styles.sideBar_List}>
            <a href="/">{`Home`}</a>
            <a href="/about">{`About`}</a>
            <a href="/products">{`Products`}</a>
            <a href="/blog">{`Blog`}</a>
            <a href="/contact">{`Contact`}</a>
          </div>
        </div>
      </>
    );
  };

  return (
    <>
      <Head>
        <title>Jainam Jewellers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="description"
          content="Wholesale jewellery store that offers a variety of custom designs made to order."
        ></meta>
      </Head>
      <Sidebar
        sidebar={<SideBarContent />}
        open={hamburger}
        onSetOpen={setHam}
        styles={{ sidebar: { background: "white" } }}
      >
        <div className={styles.layout_wrapper}>
          <div className={styles.heading}>
            <div className={styles.lineButton}>
              <img
                onClick={() => {
                  setHam(true);
                }}
                src="/img/hamBorger.svg"
                className={styles.hamBorger}
                alt="Footer Logo"
              />
            </div>
            <div className={styles.logoWrapper}>
              <img
                src="/img/logo_dark.png"
                className={styles.jainam_logo}
                alt="Header Logo"
              />
            </div>
            <div className={styles.searchButton}>
              <img
                src="/img/searchIcon.svg"
                className={styles.searchIcon}
                alt="Search Logo"
              />
            </div>
          </div>
          <div className={styles.children}>{children}</div>
          <div className={styles.footer}>
            <div className={styles.footer_link_wrapper}>
              <div className={styles.footer_link_column}>
                <div className={styles.links_header}>COMPANY</div>
                <div className={styles.footer_link_element}>About us</div>
                <div className={styles.footer_link_element}>Careers</div>
                <div className={styles.footer_link_element}>Stores</div>
              </div>
              <div className={styles.footer_link_column}>
                <div className={styles.links_header}>SUPPORT</div>
                <div className={styles.footer_link_element}>FAQ</div>
                <div className={styles.footer_link_element}>Jewellery care</div>
                <div className={styles.footer_link_element}>Our gold costs</div>
                <div className={styles.footer_link_element}>Contact Us</div>
              </div>
              <div className={styles.footer_link_column}>
                <div className={styles.links_header}>STAY IN TOUCH</div>
                <div className={styles.footer_link_element}>
                  Completely free newsletter of promotions and discounts
                </div>
                <div className={styles.email_box_small}>
                  <input placeholder="Phone / Contact" type="email" />
                  <button>CALL ME</button>
                </div>
              </div>
              <div className={styles.footer_link_column2}>
                <a className={""} href="/">
                  <img
                    src="./img/logo_dark.png"
                    className={styles.footer_jainam_logo}
                    alt="Footer Logo"
                  />
                </a>
                <div className={`${styles.footer_link_element} ${styles.all_rights}`}>
                  © 2021 Jainam Jewellers. All rights reserved.
                </div>
              </div>
            </div>
            <div className={styles.terms_wrapper}>
              <div className={styles.terms_of_use}>Terms of use</div>
              <div
                onClick={() =>
                  window.open("https://www.instagram.com/jainamjewellersmumbai")
                }
                className={styles.ig_logo_wrapper}
              >
                <img src="/img/IG_logo.svg"></img>
              </div>
              <div className={styles.privacy_policy}>Privacy policy</div>
            </div>
          </div>
        </div>
      </Sidebar>
    </>
  );
}
