import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "./Layout.module.css";
export default function Layout(props) {
  const { children } = props;

  const [hamburger, setHam] = useState(true);
  const [lang,setLang]=useState("gj")
  const handlelangChange = (e)=>{
    if (e=="gj"){
      setLang("en")
      localStorage.setItem("lang","en")
    }
    if (e=="en"){
      setLang("gj")
      localStorage.setItem("lang","gj")
    }
    window.location.reload()
  }
  useEffect(() => {
    /* window.addEventListener('scroll', handleScroll) */
    if(localStorage.getItem("lang")){
      setLang(localStorage.getItem("lang"))
    }else{
      localStorage.setItem("lang","gj")
    }
  }, []);
  return (
    <>
      <Head>
        <title>Jainam Jewellers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="description"
          content="Wholesale jewellery store that offers a variety of custom designs made to order."
        ></meta>
      </Head>
      <div className={styles.layout_wrapper}>
        <div className={styles.main_header_wrapper}>
          <div className={`${styles.top_elements}`}>
            <nav className={`${styles.navbar} navbar`}>
              {/* <a className={""} href="/">
                                <img src="./img/logo_dark.png" className={styles.jainam_logo} alt="..." />
                            </a> */}
              <div className={styles.navbar_link_group}>
                <div className={styles.navbar_link}>
                  <a  style={{fontSize : (lang=="gj")?"20px":"12px"}} className={styles.navbar_link_label} href="/">
                    {(lang=="en") && "Home"}
                    {(lang=="gj") && "ઘર"}
                  </a>
                </div>
                <div className={styles.navbar_link}>
                  <a  style={{fontSize : (lang=="gj")?"20px":"12px"}} className={styles.navbar_link_label} href="/about">
                    {(lang=="en") && "About"}
                    {(lang=="gj") && "વિશે"}
                  </a>
                </div>
                <div className={styles.navbar_link}>
                  <a  style={{fontSize : (lang=="gj")?"20px":"12px"}} className={styles.navbar_link_label} href="/products">
                    {(lang=="en") && "Products"}
                    {(lang=="gj") && "ઉત્પાદનો"}
                  </a>
                </div>
                <div className={styles.navbar_link}>
                  <a  style={{fontSize : (lang=="gj")?"20px":"12px"}} className={styles.navbar_link_label} href="/blog">
                    {(lang=="en") && "Blog"}
                    {(lang=="gj") && "બ્લોગ"}
                  </a>
                </div>
                <div className={styles.navbar_link}>
                  <a  style={{fontSize : (lang=="gj")?"20px":"12px"}} className={styles.navbar_link_label} href="/contact">
                    {(lang=="en") && "Contact"}
                    {(lang=="gj") && "સંપર્ક કરો"}
                  </a>
                </div>
                <div className={styles.navbar_link}>
                  <div onClick={()=>{handlelangChange(lang)}} style={{fontSize : (lang=="en")?"20px":"12px"}} className={styles.navbar_link_label}>
                    {(lang=="en") && "ગુજરાતી"}
                    {(lang=="gj") && "English"}
                  </div>
                </div>
              </div>
            </nav>
          </div>
        </div>
        {children}
        <footer className={styles.footer_main_wrap}>
          <div className={styles.footer_link_wrapper}>
            <div className={styles.footer_link_column}>
              <a className={""} href="/">
                <img
                  src="./img/logo_dark.png"
                  className={styles.jainam_logo}
                  alt="Footer Logo"
                />
              </a>
              <div className={styles.copyright_text}>© 2021 Jainam Jewellers. All rights reserved.</div>
            </div>
            <div className={styles.footer_link_column}>
              <div className={styles.links_header}>COMPANY</div>
              <div className={styles.footer_link_element}>About us</div>
              <div className={styles.footer_link_element}>Careers</div>
              <div className={styles.footer_link_element}>Stores</div>
            </div>
            <div className={styles.footer_link_column}>
              <div className={styles.links_header}>SUPPORT</div>
              <div className={styles.footer_link_element}>FAQ</div>
              <div className={styles.footer_link_element}>Jewellery care</div>
              <div className={styles.footer_link_element}>Our gold costs</div>
              <div className={styles.footer_link_element}>Contact Us</div>
            </div>
            <div style={{marginLeft:"auto"}} className={styles.footer_link_column}>
              <div className={styles.links_header}>STAY IN TOUCH</div>
              <div className={styles.footer_link_element}>Completely free newsletter of promotions and discounts</div>
              <div className={styles.email_box_small}>
                  <input placeholder="Phone / Contact" type="email"/>
                  <button>CALL ME</button>
              </div>
            </div>
          </div>

          <div className={styles.terms_wrapper}>
            <div className={styles.terms_of_use}>Terms of use</div>
            <div
              onClick={() =>
                window.open("https://www.instagram.com/jainamjewellersmumbai")
              }
              className={styles.ig_logo_wrapper}
            >
              <img src="/img/IG_logo.svg"></img>
            </div>
            <div className={styles.privacy_policy}>Privacy policy</div>
          </div>
        </footer>
      </div>
    </>
  );
}
