import Head from 'next/head'
import { useState, useEffect } from 'react'
import stylesm from './LayoutMobile.module.css'
export default function Layout(props) {
    const { children } = props
    const [hamburger, setHam] = useState(true);
    useEffect(() => {
        /* window.addEventListener('scroll', handleScroll) */
    }, [])
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="description" content="Wholesale jewellery store that offers a variety of custom designs made to order."></meta>
            </Head>
            <div className={stylesm.layout_wrapper}>
                <div style={{ height: hamburger ? "0rem" : "24rem"}} className={`${stylesm.colapsable_wrapper} ${hamburger?stylesm.colapsable_wrapper_hide_div:""}`}>
                    <div onClick={()=>window.location.href="/"} className={stylesm.navbar_link}>Home</div>
                    <div onClick={()=>window.location.href="/about"} className={stylesm.navbar_link}>About</div>
                    <div onClick={()=>window.location.href="/products"} className={stylesm.navbar_link}>Products</div>
                    <div onClick={()=>window.location.href="/blog"} className={stylesm.navbar_link}>Blog</div>
                    <div onClick={()=>window.location.href="/contact"} className={stylesm.navbar_link}>Contact</div>
                </div>
                <div className={` ${stylesm.overlaywrapper}`}>
                    <div >
                        <img style={{ maxHeight: "100px" }} src={`/img/logo.png`} />
                    </div>
                    <div >
                        <div className={stylesm.HamButton} onClick={() => { setHam(!hamburger) }}>
                            <div className={hamburger?"":stylesm.top_x}></div>
                            <div className={hamburger?"":stylesm.bot_x}></div>
                        </div>
                    </div>
                </div>
                <div className={`${stylesm.body_wrapper} ${!hamburger ? stylesm.expand_ham : stylesm.colapse}`}>{children}</div>
                <footer></footer>
            </div>
        </>
    )
}